### ISSUE TITLE
Build wrong in MacOS

### ISSUE THREAD

**Issue by WidgetA** [robbmcleod/cpufeature#1]
I tried to install this package. But when building cpu_x86.c and module.c, it always report an exception " duplicate symbol for architecture". Maybe it is caused by difference between clang and gcc. I fixed this problem in my repo(forked from yours): https://github.com/WidgetA/cpufeature
Just use "extern" in cpu_x86.h
I will be very glad if this information would be valuable for you.

**Comment by robbmcleod** [comment]
Thanks for the feedback. I'll have to setup some continuous integration on the to test.

**Comment by g-karthik** [comment]
@robbmcleod @WidgetA I'm getting the same issue when trying to run `pip install cpufeature` on my Mac. Can you please merge pull request https://github.com/robbmcleod/cpufeature/pull/2 to master and then update the PyPI version?

**Comment by robbmcleod** [comment]
Should be done, let me know if you have any issues.

**Comment by g-karthik** [comment]
Installation from master works, thanks @robbmcleod and @WidgetA!
