### ISSUE TITLE
Floating point exception when cpufeature is imported

### ISSUE THREAD

**Issue by dblakely** [robbmcleod/cpufeature#11]
Hi there, I'm having trouble using this library. Whenever I try to run:
```
import cpufeature
```
I get:
```
Floating point exception (core dumped)
```

My CPU info is:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz
stepping	: 1
microcode	: 0xb00002e
cpu MHz		: 2600.020
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 14
cpu cores	: 8
apicid		: 14
initial apicid	: 14
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5200.04
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

Any ideas about why it's not working?

**Comment by robbmcleod** [comment]
Are you willing to take a shot at debugging it? The function `detect_host` in 
https://github.com/robbmcleod/cpufeature/blob/master/cpufeature/cpu_x86.c is the base function called. The simplest approach is to just insert `printf` statements in sequence until you find the offending line number. If you have Linux, `valgrind` is a really nice program for basically running code in a virtual machine.

Also would be helpful to know what OS and Python version you are running.

**Comment by robbmcleod** [comment]
I added a `run_valgrind.bash` script in the root directory of the package in aad121982541882dcb74d7b2611e92375ca079e0. That should at least tell you the line number, again if you have a system that supports Valgrind.

**Comment by robbmcleod** [comment]
Closing as is stale.

**Comment by jeffrey4l** [comment]
may related to issue #17  ?
