### ISSUE TITLE
Fails to compile on Apple Silicon

### ISSUE THREAD

**Issue by alexreinking** [robbmcleod/cpufeature#13]
On Apple Silicon the native extensions fail to compile with:

```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -Icpufeature -I/Users/redacted/.pyenv/versions/3.9.6/include/python3.9 -c cpufeature/cpu_x86.c -o build/temp.macosx-11.5-arm64-3.9/cpufeature/cpu_x86.o
    cpufeature/cpu_x86.c:21:5: error: "No cpuid intrinsic defined for processor architecture."
    #   error "No cpuid intrinsic defined for processor architecture."
        ^
    cpufeature/cpu_x86.c:48:35: error: implicit declaration of function 'xgetbv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            uint64_t xcrFeatureMask = xgetbv(_XCR_XFEATURE_ENABLED_MASK);
                                      ^
    cpufeature/cpu_x86.c:48:42: error: use of undeclared identifier '_XCR_XFEATURE_ENABLED_MASK'
            uint64_t xcrFeatureMask = xgetbv(_XCR_XFEATURE_ENABLED_MASK);
                                             ^
    cpufeature/cpu_x86.c:59:31: error: implicit declaration of function 'xgetbv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        uint64_t xcrFeatureMask = xgetbv(_XCR_XFEATURE_ENABLED_MASK);
                                  ^
    cpufeature/cpu_x86.c:59:38: error: use of undeclared identifier '_XCR_XFEATURE_ENABLED_MASK'
        uint64_t xcrFeatureMask = xgetbv(_XCR_XFEATURE_ENABLED_MASK);
                                         ^
    cpufeature/cpu_x86.c:150:23: error: implicit declaration of function 'hardware_concurrency' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        totalSystemProc = hardware_concurrency();
                          ^
```

It would be more useful if instead of failing to build, the module reported either (conservatively) "false" or "unknown" in such cases.

**Comment by robbmcleod** [comment]
As it says in the first line of the README, "CPUFeature is a tool for detecting CPU features on x86/AMD64 processors."

**Comment by alexreinking** [comment]
@robbmcleod - that does not in any way imply that it should fail to build on Apple Silicon. It should just return false for everything. In particular, including `cpufeature` in a `requirements.txt` file causes failures in `pip` when running `pip install -r requirements.txt`.

How should this package be used in cross-platform projects? How would you suggest I check whether it's safe to use this library?

**Comment by robbmcleod** [comment]
@alexreinking 

> How should this package be used in cross-platform projects? 

It should not be used in projects that do not support the x86/AMD64 standard.

> How would you suggest I check whether it's safe to use this library?

Ask Apple Inc. They made the business decision that created this problem, they can fix it.

**Comment by alexreinking** [comment]
> It should not be used in projects that do not support the x86/AMD64 standard.

My project specifically _does_ support AMD64. It _also_ wants to support other ISAs.

> Ask Apple Inc. They made the business decision that created this problem, they can fix it.

No they did not. Apple did not invent ARM. This will also cause the same failure on aarch64 Linux.
